package com.acme.gui;

import br.com.acme.model.AcademicLibrary;
import br.com.acme.model.Article;
import br.com.acme.model.Author;
import br.com.acme.model.Journal;
import br.com.acme.model.Publication;
import br.com.acme.model.Publisher;
import com.acme.logic.ALManager;
import com.acme.logic.LogErros;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class AddArticleForm extends javax.swing.JDialog {

    /**
     * Declaração de atributos e criação.
     */
    private List<Author> authors;
    private ArrayList<String> keyWords;
    AcademicLibrary library;
    private Article article ;
    private Publisher publisher;
    Journal journal;

    /**
     * Costrutor que criará um form
     *
     * @param parent
     * @param modal
     */
    public AddArticleForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        keyWords = new ArrayList<>();
        article = new Article();
        publisher = new Publisher();
        authors = new ArrayList<>();
        library = ALManager.getInstance();
        journal = new Journal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlArticle = new javax.swing.JLabel();
        jlTittle = new javax.swing.JLabel();
        jlYear = new javax.swing.JLabel();
        jlVolume = new javax.swing.JLabel();
        jlLanguage = new javax.swing.JLabel();
        jlISSN = new javax.swing.JLabel();
        jlStartPage = new javax.swing.JLabel();
        jlEndPage = new javax.swing.JLabel();
        jtfTittle = new javax.swing.JTextField();
        jtfYear = new javax.swing.JTextField();
        jtfVolume = new javax.swing.JTextField();
        jtfLanguage = new javax.swing.JTextField();
        jtfISSN = new javax.swing.JTextField();
        jtfStartPage = new javax.swing.JTextField();
        jtfEndPage = new javax.swing.JTextField();
        jbAddAuthor = new javax.swing.JButton();
        jbAddKeyword = new javax.swing.JButton();
        jpJournal = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        jlImpactFactor = new javax.swing.JLabel();
        jlPublisher = new javax.swing.JLabel();
        jlCountry = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfImpactFactor = new javax.swing.JTextField();
        jtfPublisher = new javax.swing.JTextField();
        jtfCountry = new javax.swing.JTextField();
        jbOK = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Article");

        jlArticle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jlArticle.setText("Article");

        jlTittle.setText("Tittle:");

        jlYear.setText("Year:");

        jlVolume.setText("Volume:");
        jlVolume.setToolTipText("");

        jlLanguage.setText("Langague:");

        jlISSN.setText("ISSN:");

        jlStartPage.setText("Start Page:");

        jlEndPage.setText("End Page:");

        jbAddAuthor.setText("Add Author");
        jbAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAuthorActionPerformed(evt);
            }
        });

        jbAddKeyword.setText("Add Keyword");
        jbAddKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddKeywordActionPerformed(evt);
            }
        });

        jpJournal.setBorder(javax.swing.BorderFactory.createTitledBorder("Journal"));
        jpJournal.setToolTipText("Journal");

        jlName.setText("Name:");

        jlImpactFactor.setText("Impact Factor:");

        jlPublisher.setText("Publisher:");

        jlCountry.setText("Country:");

        javax.swing.GroupLayout jpJournalLayout = new javax.swing.GroupLayout(jpJournal);
        jpJournal.setLayout(jpJournalLayout);
        jpJournalLayout.setHorizontalGroup(
            jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpJournalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpJournalLayout.createSequentialGroup()
                        .addComponent(jlName)
                        .addGap(18, 18, 18)
                        .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpJournalLayout.createSequentialGroup()
                        .addComponent(jlImpactFactor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfImpactFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpJournalLayout.createSequentialGroup()
                            .addComponent(jlPublisher)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfPublisher))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpJournalLayout.createSequentialGroup()
                            .addComponent(jlCountry)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpJournalLayout.setVerticalGroup(
            jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpJournalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlImpactFactor)
                    .addComponent(jtfImpactFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPublisher)
                    .addComponent(jtfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCountry)
                    .addComponent(jtfCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jbOK.setText("OK");
        jbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOKMouseClicked(evt);
            }
        });

        jbClose.setText("Close");
        jbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlStartPage)
                    .addComponent(jlISSN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlLanguage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlVolume, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlYear, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfStartPage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfISSN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfVolume, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jpJournal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jlArticle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlEndPage)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbAddAuthor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbAddKeyword)))
                                .addGap(10, 10, 10)
                                .addComponent(jtfEndPage, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jlTittle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jbOK)
                        .addGap(52, 52, 52)
                        .addComponent(jbClose)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlArticle)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTittle)
                    .addComponent(jtfTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddAuthor)
                    .addComponent(jbAddKeyword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlYear)
                            .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlVolume)
                            .addComponent(jtfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLanguage)
                            .addComponent(jtfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlISSN)
                            .addComponent(jtfISSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlStartPage)
                            .addComponent(jtfStartPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEndPage)
                            .addComponent(jtfEndPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpJournal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbClose))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt Captura de ação sobre botão Close.
     */
    private void jbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jbCloseMouseClicked

    /**
     * Ao ocorrer o evento então se todos os campos não estiverem vazios será
     * adicionado um novo artigo. Infelizmente ainda não está funcional.
     *
     * @param evt Captura ação sobre botão OK.
     */
    private void jbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOKMouseClicked
        try {
            String t = jtfTittle.getText();

            if (t.length() != 0) {
                article.setTitle(t);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Tittle' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfTittle.requestFocus();
            }

            String y = jtfYear.getText();
            if (y.length() != 0) {
                Short s = Short.parseShort(y);
                article.setYear(s);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Year' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfYear.requestFocus();
            }

            String v = jtfVolume.getText();
            if (v.length() != 0) {
                Byte bt = Byte.valueOf(v);
                article.setVolume(bt);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Volume' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfVolume.requestFocus();
            }

            String l = jtfLanguage.getText();
            if (l.length() != 0) {

            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Language' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfLanguage.requestFocus();
            }

            String i = jtfISSN.getText();
            if (i.length() != 0) {
                long z = Long.parseLong(i);
                article.setIssn(z);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'ISSN' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfISSN.requestFocus();
            }

            String start = jtfStartPage.getText();
            if (start.length() != 0) {
                Short z = Short.parseShort(start);
                article.setStartPage(z);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Start Page' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfStartPage.requestFocus();
            }

            String end = jtfEndPage.getText();
            if (start.length() != 0) {
                Short en = Short.parseShort(end);
                article.setEndPage(en);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'End Page' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfEndPage.requestFocus();
            }

            if (jtfCountry.getText().length() != 0 && jtfImpactFactor.getText().length() != 0 && jtfName.getText().length() != 0 && jtfPublisher.getText().length() != 0) {
                String im = jtfImpactFactor.getText();
                byte impact = Byte.valueOf(im);
                publisher.setCountry(jtfCountry.getText());
                publisher.setName(jtfPublisher.getText());
                journal.setName(jtfName.getText());
                journal.setImpactFactor(impact);
                journal.setPublisher(publisher);
                article.setJournal(journal);
                library.addPublication(article);
                
                JOptionPane.showMessageDialog(null, "Article Saved");
                this.dispose();

            }

        } catch (Exception e) {
            System.out.println(e);
            System.out.println("");
            System.out.println(e.getMessage());
            LogErros.gravarArquivo(e);
        }
    }//GEN-LAST:event_jbOKMouseClicked

    /**
     * Criará um novo form de AuthorForm
     *
     * @param evt Captura de evento sobre ação do botao AddAuthot
     */
    private void jbAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAuthorActionPerformed
        AuthorForm at = new AuthorForm((Frame) this.getParent(), true, authors, article);
        at.setVisible(true);
    }//GEN-LAST:event_jbAddAuthorActionPerformed

    /**
     * Criará um form de KeyWordform
     *
     * @param evt Captura de ação sobre botão AddKeyword
     */
    private void jbAddKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddKeywordActionPerformed
        KeywordForm ky = new KeywordForm((Frame) this.getParent(), true, keyWords);
        ky.setVisible(true);
    }//GEN-LAST:event_jbAddKeywordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddAuthor;
    private javax.swing.JButton jbAddKeyword;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbOK;
    private javax.swing.JLabel jlArticle;
    private javax.swing.JLabel jlCountry;
    private javax.swing.JLabel jlEndPage;
    private javax.swing.JLabel jlISSN;
    private javax.swing.JLabel jlImpactFactor;
    private javax.swing.JLabel jlLanguage;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPublisher;
    private javax.swing.JLabel jlStartPage;
    private javax.swing.JLabel jlTittle;
    private javax.swing.JLabel jlVolume;
    private javax.swing.JLabel jlYear;
    private javax.swing.JPanel jpJournal;
    private javax.swing.JTextField jtfCountry;
    private javax.swing.JTextField jtfEndPage;
    private javax.swing.JTextField jtfISSN;
    private javax.swing.JTextField jtfImpactFactor;
    private javax.swing.JTextField jtfLanguage;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPublisher;
    private javax.swing.JTextField jtfStartPage;
    private javax.swing.JTextField jtfTittle;
    private javax.swing.JTextField jtfVolume;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables
}
