package com.acme.gui;

import br.com.acme.model.AcademicLibrary;
import br.com.acme.model.Author;
import br.com.acme.model.Book;
import br.com.acme.model.Publication;
import com.acme.logic.ALManager;
import com.acme.logic.LogErros;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class AddBookForm extends javax.swing.JDialog {

    /**
     * Declaração e criação de um author e um book, declaração de library.
     */
    public List<Author> authors = new ArrayList<>();
    private AcademicLibrary library;
    private Book book = new Book();

    /**
     * Este construtor criará o form, e carregará o library usando o metodo
     * getInstance contido na classe ALManager.
     *
     * @param parent
     * @param modal
     */
    public AddBookForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //authors = new ArrayList<>();
        library = ALManager.getInstance();
    }

    /**
     *
     * @param au
     */
    public AddBookForm(Author au) {
        authors.add(au);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlBook = new javax.swing.JLabel();
        jlTittle = new javax.swing.JLabel();
        jlYear = new javax.swing.JLabel();
        jlVolume = new javax.swing.JLabel();
        jlLanguage = new javax.swing.JLabel();
        jlISBN = new javax.swing.JLabel();
        jlPages = new javax.swing.JLabel();
        jtfTittle = new javax.swing.JTextField();
        jtfYear = new javax.swing.JTextField();
        jtfVolume = new javax.swing.JTextField();
        jtfLanguage = new javax.swing.JTextField();
        jtfISBN = new javax.swing.JTextField();
        jtfPages = new javax.swing.JTextField();
        jbAddAuthor = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book");

        jlBook.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jlBook.setText("Book");

        jlTittle.setText("Tittle:");

        jlYear.setText("Year:");
        jlYear.setToolTipText("");

        jlVolume.setText("Volume:");

        jlLanguage.setText("Language:");

        jlISBN.setText("ISBN:");

        jlPages.setText("Pages:");

        jbAddAuthor.setText("Add Author");
        jbAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAuthorActionPerformed(evt);
            }
        });

        jbOK.setText("OK");
        jbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOKMouseClicked(evt);
            }
        });

        jbClose.setText("Close");
        jbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jlBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLanguage)
                                    .addComponent(jlISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlPages, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlVolume, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlYear, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPages, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jbAddAuthor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlTittle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbOK)
                .addGap(35, 35, 35)
                .addComponent(jbClose)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlBook)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTittle)
                    .addComponent(jtfTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAddAuthor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlYear)
                    .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlVolume)
                    .addComponent(jtfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLanguage)
                    .addComponent(jtfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBN)
                    .addComponent(jtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPages)
                    .addComponent(jtfPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt Captura de ação sobre o botão Close.
     */
    private void jbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jbCloseMouseClicked

    /**
     * Quando ocorrer o evento então será adicionado um book usando o metodo
     * addPublication quando os campos nao forem vazios. Infelizmente está
     * ocorrendo falhas ao adicionar um author.
     *
     * @param evt Captura de ação sobre o botão OK.
     */
    private void jbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOKMouseClicked
        try {
            String t = jtfTittle.getText();

            if (t.length() != 0) {
                book.setTitle(t);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Tittle' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfTittle.requestFocus();
            }

            String y = jtfYear.getText();
            if (y.length() != 0) {
                Short s = Short.parseShort(y);
                book.setYear(s);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Year' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfYear.requestFocus();
            }

            String v = jtfVolume.getText();
            if (v.length() != 0) {
                Byte bt = Byte.valueOf(v);
                book.setVolume(bt);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Volume' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfVolume.requestFocus();
            }

            String l = jtfLanguage.getText();
            if (l.length() != 0) {
                book.setLanguage(l);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Language' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfLanguage.requestFocus();
            }

            String i = jtfISBN.getText();
            if (i.length() != 0) {
                long lo = Long.parseLong(i);
                book.setIsbn(lo);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'ISBN' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfISBN.requestFocus();
            }

            String p = jtfPages.getText();
            if (p.length() != 0) {
                Short pag = Short.parseShort(p);
                book.setPages(pag);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Pages' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfPages.requestFocus();
            }

            if (t.length() != 0 && y.length() != 0 && v.length() != 0 && l.length() != 0 && i.length() != 0 && p.length() != 0) {
                library.addPublication(book);
                limpa();
                JOptionPane.showMessageDialog(null, "Book Added");
            } else {
                JOptionPane.showMessageDialog(this, "Book not Addedd, Campo em branco!", "Aviso", JOptionPane.OK_OPTION);
            }

        } catch (Exception e) {
            LogErros.gravarArquivo(e);
            System.out.println(e);
        }
    }//GEN-LAST:event_jbOKMouseClicked

    /**
     * Criará o form AuthorForm e setando sua visiblidade.
     *
     * @param evt Captura de ação sobre o botão AddAuthor
     */
    private void jbAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAuthorActionPerformed
        AuthorForm at = new AuthorForm((Frame) this.getParent(), true, authors, book);
        at.setVisible(true);
    }//GEN-LAST:event_jbAddAuthorActionPerformed

    /**
     * Este metodo é para deixar os campos dos textField's em branco passando a
     * eles uma string 'vazia' "".
     */
    private void limpa() {
        jtfTittle.setText("");
        jtfYear.setText("");
        jtfVolume.setText("");
        jtfLanguage.setText("");
        jtfISBN.setText("");
        jtfPages.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddAuthor;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbOK;
    private javax.swing.JLabel jlBook;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlLanguage;
    private javax.swing.JLabel jlPages;
    private javax.swing.JLabel jlTittle;
    private javax.swing.JLabel jlVolume;
    private javax.swing.JLabel jlYear;
    private javax.swing.JTextField jtfISBN;
    private javax.swing.JTextField jtfLanguage;
    private javax.swing.JTextField jtfPages;
    private javax.swing.JTextField jtfTittle;
    private javax.swing.JTextField jtfVolume;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables
}
