package com.acme.gui;

import br.com.acme.model.AcademicLibrary;
import br.com.acme.model.Author;
import br.com.acme.model.Publication;
import com.acme.logic.ALManager;
import com.acme.logic.LogErros;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class AuthorForm extends javax.swing.JDialog {

    int count = 0;
    AcademicLibrary library;
    private Author author = new Author();
    private List<Author> authors;
    Publication publications;

    /**
     * Creates new form AuthorForm
     *
     * @param parent
     * @param modal
     * @param authors
     * @param publications
     */
    public AuthorForm(java.awt.Frame parent, boolean modal, List<Author> authors, Publication publications) {
        super(parent, modal);
        initComponents();
        library = ALManager.getInstance();
        this.authors = authors;
        this.publications = publications;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAddAuthor = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlAfiliation = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfAfiliation = new javax.swing.JTextField();
        jbOK = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();
        jcblsCorresponding = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Author");

        jlAddAuthor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlAddAuthor.setText("Add Author");

        jlName.setText("Name:");

        jlEmail.setText("E-Mail:");

        jlAfiliation.setText("Afiliation:");

        jbOK.setText("OK");
        jbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOKMouseClicked(evt);
            }
        });

        jbClose.setText("Close");
        jbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCloseMouseClicked(evt);
            }
        });

        jcblsCorresponding.setText("Corresponding author?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jbOK)
                        .addGap(43, 43, 43)
                        .addComponent(jbClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlAddAuthor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEmail)
                            .addComponent(jlName)
                            .addComponent(jlAfiliation))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfAfiliation, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcblsCorresponding))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlAddAuthor)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlAfiliation)
                    .addComponent(jtfAfiliation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jcblsCorresponding)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbClose))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jbCloseMouseClicked

    private void jbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOKMouseClicked

        try {
            String n = jtfName.getText();

            if (n.length() != 0) {
                author.setName(n);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Name' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfName.requestFocus();
            }

            String e = jtfEmail.getText();
            if (e.length() != 0) {
                author.setEmail(e);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'E-Mail' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfEmail.requestFocus();
            }

            String a = jtfAfiliation.getText();
            if (a.length() != 0) {
                author.setAfiliation(a);
            } else {
                JOptionPane.showMessageDialog(this, "O campo 'Afiliation' não pode ser vazio!", "Aviso", JOptionPane.OK_OPTION);
                jtfAfiliation.requestFocus();
            }

            if (a.length() != 0 && e.length() != 0 && n.length() != 0) {
              //  authors.add(author);
                publications.addAuthor(author);
                JOptionPane.showMessageDialog(null, "Author Added");
                limpa();
            } else {
                JOptionPane.showMessageDialog(this, "Author not Addedd, Campo em branco!", "Aviso", JOptionPane.OK_OPTION);
            }

        } catch (Exception e) {
            System.out.println(e);
            LogErros.gravarArquivo(e);
        }
    }//GEN-LAST:event_jbOKMouseClicked

    /**
     * Este metodo é para deixar os campos dos textField's em branco passando a
     * eles uma string 'vazia' "".
     */
    private void limpa() {
        jtfName.setText("");
        jtfEmail.setText("");
        jtfAfiliation.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbOK;
    private javax.swing.JCheckBox jcblsCorresponding;
    private javax.swing.JLabel jlAddAuthor;
    private javax.swing.JLabel jlAfiliation;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlName;
    private javax.swing.JTextField jtfAfiliation;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
