package com.acme.gui;

import br.com.acme.model.AcademicLibrary;
import br.com.acme.model.User;
import com.acme.logic.ALManager;
import com.acme.logic.LogErros;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class LoginForm extends javax.swing.JDialog {

    /**
     * Declaração de library (AcademicLibrary)
     */
    private AcademicLibrary library;
    File f = new File("c:/library.ser");

    /**
     * Cria nova form LoginForm
     */
    public LoginForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public void check() {
        try {
            if (!f.exists()) {
                jlInfo.setText("Login: root    |    Password: 1234");
                User u = new User();
                u.setLogin("root");
                u.setPassword("@!%#");
                library = ALManager.getInstance();
                library.getUsers().put("root", u);
                ALManager.persistLibrary(f);
            }
            if (f.exists()) {
                ALManager.loadLibrary(f);
                library = ALManager.getInstance();
                Collection<User> users = library.getUsers().values();
                if (users.size() > 1) {
                    User us = library.getUsers().get("root");
                    System.out.println(us.getPassword());
                    if (us.getPassword().equalsIgnoreCase("@!%#")) {
                        library.getUsers().remove("root");
                        ALManager.persistLibrary(f);
                    }
                }
            }
        } catch (Exception e) {
            LogErros.gravarArquivo(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAcademicLibraryControlSystem = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jbValidate = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jlInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        jlAcademicLibraryControlSystem.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlAcademicLibraryControlSystem.setText("AcademicLibraryControlSystem");

        jlLogin.setText("Login:");

        jlPassword.setText("Password:");

        jpfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfPasswordKeyPressed(evt);
            }
        });

        jbValidate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acme/gui/icons/accept.png"))); // NOI18N
        jbValidate.setText("Validate");
        jbValidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbValidateMouseClicked(evt);
            }
        });

        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/acme/gui/icons/cross.png"))); // NOI18N
        jbCancel.setText("Cancel");
        jbCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addComponent(jlAcademicLibraryControlSystem)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPassword)
                                .addGap(38, 38, 38)
                                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbValidate)
                                .addGap(50, 50, 50)
                                .addComponent(jbCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlLogin)
                                .addGap(54, 54, 54)
                                .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlAcademicLibraryControlSystem)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPassword)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jlInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbValidate)
                    .addComponent(jbCancel))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Quando ocorrer este evento então surgirá uma janela com questionamento
     * sobre a saida do usuário do sistema.
     *
     * @param evt Captura ação sobre botão Cancel
     */
    private void jbCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelMouseClicked
        int result = JOptionPane.showConfirmDialog(this, "Voce quer realmente sair?", "Pergunta", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbCancelMouseClicked

    /**
     * Quando este evento ocorrer então será lido o arquivo do disco contendo os
     * usuários. Também se aplica a comparação para saber se existem usuários
     * com os dados digitados nos campos.
     *
     * @param evt Captura de ação sobre o botão Validade.
     */
    private void jbValidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbValidateMouseClicked
        try {
            try {
                ALManager.loadLibrary(f);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            } catch (ClassNotFoundException ex) {
                System.out.println(ex.getMessage());
            }

            String login = jtfLogin.getText();
            String senha = new String(jpfPassword.getPassword());
            String passwor = Encrypt.cripto(senha);
            library = ALManager.getInstance();

            User u = library.getUsers().get(login);
            if (library.getUsers().containsKey(login)) {
                if (u.getPassword().equalsIgnoreCase(passwor)) {
                    MainWindowForm j = new MainWindowForm();
                    j.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Login e/ou Senha Incorretos", "Aviso", JOptionPane.OK_OPTION);
                    jtfLogin.setText("");
                    jtfLogin.requestFocus();
                    jpfPassword.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Login e/ou Senha Incorretos", "Aviso", JOptionPane.OK_OPTION);
                jtfLogin.setText("");
                jtfLogin.requestFocus();
                jpfPassword.setText("");
            }
        } catch (Exception e) {
            LogErros.gravarArquivo(e);
        }

    }//GEN-LAST:event_jbValidateMouseClicked

    private void jpfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbValidateMouseClicked(null);
        }
    }//GEN-LAST:event_jpfPasswordKeyPressed

    public LoginForm() {
        initComponents();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbValidate;
    private javax.swing.JLabel jlAcademicLibraryControlSystem;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfLogin;
    // End of variables declaration//GEN-END:variables
}
