package Forms;

import Data.ResultSetTableModel;
import static Forms.frame.url;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Mateus
 */
public class queryForm extends javax.swing.JFrame {

    static final String url = "jdbc:mysql://localhost/lp";
    static final String password = "@grimefocus1";
    static final String user = "root";
    ResultSetTableModel table;
    int line = 0;
    String full = "";
    String dois = "";
    String um = "";
    String tres = "";
    String quatro = "";
    String cinco = "";
    String seis = "";

    /**
     * Creates new form queryForm
     */
    public queryForm() throws SQLException {
        this.table = new ResultSetTableModel(url, user, password, "select * from cliente");
        initComponents();
        jtaQuery.setText("select * from cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConsultVendedor = new javax.swing.JPanel();
        jbConsulVendedorName = new javax.swing.JButton();
        jbConsulVendedorCod = new javax.swing.JButton();
        jtfVendName = new javax.swing.JTextField();
        jtfConsulVendedorCod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbConsultProdName = new javax.swing.JButton();
        jbConsultProdCod = new javax.swing.JButton();
        jtfProdName = new javax.swing.JTextField();
        jtfProdCod = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbNameCli = new javax.swing.JButton();
        jbCodCli = new javax.swing.JButton();
        jtfNameCli = new javax.swing.JTextField();
        jtfCodCli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaQuery = new javax.swing.JTextArea();
        jbQuery = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUltimasConsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpConsultVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Vendedor"));
        jpConsultVendedor.setToolTipText("Consultar Vendedor");
        jpConsultVendedor.setName(""); // NOI18N

        jbConsulVendedorName.setText("OK");
        jbConsulVendedorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsulVendedorNameActionPerformed(evt);
            }
        });

        jbConsulVendedorCod.setText("OK");
        jbConsulVendedorCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsulVendedorCodActionPerformed(evt);
            }
        });

        jLabel1.setText("Digitite o nome ou parte do nome do Vendedor:");

        jLabel2.setText("Digite o codigo do Vendedor:");

        javax.swing.GroupLayout jpConsultVendedorLayout = new javax.swing.GroupLayout(jpConsultVendedor);
        jpConsultVendedor.setLayout(jpConsultVendedorLayout);
        jpConsultVendedorLayout.setHorizontalGroup(
            jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultVendedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfVendName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConsulVendedorName)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultVendedorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(jtfConsulVendedorCod, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConsulVendedorCod)
                .addGap(30, 30, 30))
        );
        jpConsultVendedorLayout.setVerticalGroup(
            jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbConsulVendedorName)
                    .addGroup(jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfVendName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfConsulVendedorCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsulVendedorCod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Produto"));

        jLabel3.setText("Digite o nome ou parte no nome do Produto:");

        jLabel4.setText("Digite o codigo do Produto:");

        jbConsultProdName.setText("OK");
        jbConsultProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultProdNameActionPerformed(evt);
            }
        });

        jbConsultProdCod.setText("OK");
        jbConsultProdCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultProdCodActionPerformed(evt);
            }
        });

        jtfProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfProdName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConsultProdName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jbConsultProdCod)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jbConsultProdName)
                    .addComponent(jtfProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultProdCod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Cliente"));

        jLabel5.setText("Digite o nome ou parte do nome do Cliente:");

        jLabel6.setText("Digite o CPF do Cliente:");

        jbNameCli.setText("OK");
        jbNameCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNameCliActionPerformed(evt);
            }
        });

        jbCodCli.setText("OK");
        jbCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCodCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfNameCli)
                        .addGap(18, 18, 18)
                        .addComponent(jbNameCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jtfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jbCodCli)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jbNameCli)
                    .addComponent(jtfNameCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCodCli)
                    .addComponent(jtfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(table);
        jScrollPane1.setViewportView(jTable1);

        jtaQuery.setColumns(20);
        jtaQuery.setRows(5);
        jScrollPane2.setViewportView(jtaQuery);

        jbQuery.setText("Query");
        jbQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQueryActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ultimas Linhas de Consulta"));
        jPanel3.setToolTipText("");

        jtUltimasConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane3.setViewportView(jtUltimasConsultas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(jbQuery)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpConsultVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jpConsultVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jbQuery))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsulVendedorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsulVendedorNameActionPerformed
        try {
            table.searchVendedorName(jtfVendName.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfNameCli.setText("");
            jtfCodCli.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsulVendedorNameActionPerformed

    private void jtfProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdNameActionPerformed

    private void jbQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQueryActionPerformed
        String text = jtaQuery.getText();
        populate();
        try {
            this.table.setQuery(text);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbQueryActionPerformed

    private void jbNameCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNameCliActionPerformed
        try {
            table.searchCliName(jtfNameCli.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbNameCliActionPerformed

    private void jbCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCodCliActionPerformed
        try {
            table.searchCliCod(jtfCodCli.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbCodCliActionPerformed

    private void jbConsultProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultProdNameActionPerformed
        try {
            table.searchProName(jtfProdName.getText());
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
            jtfCodCli.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsultProdNameActionPerformed

    private void populate() {
        TableModel mod = jtUltimasConsultas.getModel();
        try {
            full = jtUltimasConsultas.getValueAt(6, 0).toString();
        } catch (Exception ex) {
        }
        if (full.length() != 0) {
            um = jtUltimasConsultas.getValueAt(0, 0).toString();
            dois = jtUltimasConsultas.getValueAt(1, 0).toString();
            tres = jtUltimasConsultas.getValueAt(2, 0).toString();
            quatro = jtUltimasConsultas.getValueAt(3, 0).toString();
            cinco = jtUltimasConsultas.getValueAt(4, 0).toString();
            seis = jtUltimasConsultas.getValueAt(5, 0).toString();

            mod.setValueAt(jtaQuery.getText(), 0, 0);
            mod.setValueAt(um, 1, 0);
            mod.setValueAt(dois, 2, 0);
            mod.setValueAt(tres, 3, 0);
            mod.setValueAt(quatro, 4, 0);
            mod.setValueAt(cinco, 5, 0);
            mod.setValueAt(seis, 6, 0);
        } else {
            mod.setValueAt(jtaQuery.getText(), line, 0);
            line++;
        }
    }

    private void jbConsulVendedorCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsulVendedorCodActionPerformed
        try {
            table.searchVendedorCod(jtfConsulVendedorCod.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfNameCli.setText("");
            jtfCodCli.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsulVendedorCodActionPerformed

    private void jbConsultProdCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultProdCodActionPerformed
        try {
            table.searchProCod(jtfProdCod.getText());
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
            jtfCodCli.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsultProdCodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCodCli;
    private javax.swing.JButton jbConsulVendedorCod;
    private javax.swing.JButton jbConsulVendedorName;
    private javax.swing.JButton jbConsultProdCod;
    private javax.swing.JButton jbConsultProdName;
    private javax.swing.JButton jbNameCli;
    private javax.swing.JButton jbQuery;
    private javax.swing.JPanel jpConsultVendedor;
    private javax.swing.JTable jtUltimasConsultas;
    private javax.swing.JTextArea jtaQuery;
    private javax.swing.JTextField jtfCodCli;
    private javax.swing.JTextField jtfConsulVendedorCod;
    private javax.swing.JTextField jtfNameCli;
    private javax.swing.JTextField jtfProdCod;
    private javax.swing.JTextField jtfProdName;
    private javax.swing.JTextField jtfVendName;
    // End of variables declaration//GEN-END:variables
}
