package Teste;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mateus
 */
public class FormC extends javax.swing.JFrame {

    ConnectClass data;

    /**
     * Creates new form FormC
     */
    public FormC() {
        try {
            data = new ConnectClass();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro");
        }
        initComponents();
        jtNumberOfDays.setText(data.numberOfDays());
        jtfDay.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDeleteDay = new javax.swing.JButton();
        jbAddDay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtComentArea = new javax.swing.JTextArea();
        jbDeleteAll = new javax.swing.JButton();
        jlDay = new javax.swing.JLabel();
        jtfDay = new javax.swing.JTextField();
        jbShow = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtNumberOfDays = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbDeleteDay.setText("Delete Day");
        jbDeleteDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteDayActionPerformed(evt);
            }
        });

        jbAddDay.setText("Add Day");
        jbAddDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddDayActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentário"));
        jPanel1.setToolTipText("");

        jtComentArea.setColumns(20);
        jtComentArea.setRows(5);
        jScrollPane1.setViewportView(jtComentArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbDeleteAll.setText("Delete All Day");
        jbDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteAllActionPerformed(evt);
            }
        });

        jlDay.setText("Day:");

        jbShow.setText("Show");
        jbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowActionPerformed(evt);
            }
        });

        jbExit.setText("Exit");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jLabel1.setText("Has");

        jLabel2.setText("days stored");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAddDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbDeleteDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jbShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeleteAll)
                        .addGap(18, 18, 18)
                        .addComponent(jbExit)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNumberOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddDay)
                    .addComponent(jbDeleteDay)
                    .addComponent(jbDeleteAll)
                    .addComponent(jlDay)
                    .addComponent(jtfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbShow)
                    .addComponent(jbExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNumberOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddDayActionPerformed
        if (jtComentArea.getText().length() == 0 && jtfDay.getText().length() != 0) {
            data.addDay(jtfDay.getText());
            jtfDay.setText("");
            jtNumberOfDays.setText(data.numberOfDays());
        } else if (jtComentArea.getText().length() != 0 && jtfDay.getText().length() != 0) {
            data.addDayComentary(jtfDay.getText(), jtComentArea.getText());
            jtfDay.setText("");
            jtComentArea.setText("");
        } else {
            jtNumberOfDays.setText(data.numberOfDays());
            JOptionPane.showMessageDialog(null, "Please, insert a day!", "Mensagem", 2);
        }
    }//GEN-LAST:event_jbAddDayActionPerformed

    private void jbDeleteDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteDayActionPerformed
        if (jtfDay.getText().length() != 0) {
            data.deleteDay(jtfDay.getText());
            jtfDay.setText("");
            jtNumberOfDays.setText(data.numberOfDays());
        } else {
            JOptionPane.showMessageDialog(null, "Please, insert a day!", "Mensagem", 2);
        }
    }//GEN-LAST:event_jbDeleteDayActionPerformed

    private void jbDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteAllActionPerformed
        String message = "Deseja realmente apagar tudo?";
        String title = "Confirmação";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            data.deleteAllDays();
            jtNumberOfDays.setText(data.numberOfDays());
        }
    }//GEN-LAST:event_jbDeleteAllActionPerformed

    private void jbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowActionPerformed
        ShowAll show = new ShowAll();
        show.setVisible(true);
        jtNumberOfDays.setText(data.numberOfDays());
    }//GEN-LAST:event_jbShowActionPerformed

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        data.disconnectFromDatabase();
        System.exit(0);
    }//GEN-LAST:event_jbExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAddDay;
    private javax.swing.JButton jbDeleteAll;
    private javax.swing.JButton jbDeleteDay;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbShow;
    private javax.swing.JLabel jlDay;
    private javax.swing.JTextArea jtComentArea;
    private javax.swing.JTextField jtNumberOfDays;
    private javax.swing.JTextField jtfDay;
    // End of variables declaration//GEN-END:variables
}
