package com.acme.gui;

/**
 *
 * @author Mateus
 */


public class NewForm extends javax.swing.JFrame {

    /**
     * Creates new form NewForm
     */
    public NewForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbNewBook = new javax.swing.JButton();
        jbNewArticle = new javax.swing.JButton();
        jbNewUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Você deseja um novo...");

        jbNewBook.setText("Book");
        jbNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewBookActionPerformed(evt);
            }
        });

        jbNewArticle.setText("Article");
        jbNewArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewArticleActionPerformed(evt);
            }
        });

        jbNewUser.setText("User");
        jbNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbNewUser)
                            .addComponent(jbNewBook)
                            .addComponent(jbNewArticle))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNewBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNewArticle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewBookActionPerformed
       AddBookForm e = new AddBookForm(this, true);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbNewBookActionPerformed

    private void jbNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewUserActionPerformed
        CreateAccountForm j = new CreateAccountForm(this, true);
        j.setVisible(true);   
        this.dispose();
    }//GEN-LAST:event_jbNewUserActionPerformed

    private void jbNewArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewArticleActionPerformed
        AddArticleForm q = new AddArticleForm(this, true);
        q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbNewArticleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbNewArticle;
    private javax.swing.JButton jbNewBook;
    private javax.swing.JButton jbNewUser;
    // End of variables declaration//GEN-END:variables
}
