package Forms;

import Data.ModelTable;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 * Este form tem como objetivo proporcionar a interação entre as funções diponiveis
 * no form para realizar tarefas conjuntas ao banco de dados
 * @author Mateus
 */
public class queryForm extends javax.swing.JFrame {

    static final String url = "jdbc:mysql://localhost/lp";
    String login;
    String pw;
    ModelTable table;
    int line = 0;
    String full = "";
    String dois = "";
    String um = "";
    String tres = "";
    String quatro = "";
    String cinco = "";
    String seis = "";

    /**
     * Creates new form queryForm
     * Cria novo objeto da classe ModelTable para que
     * seja criado o modelo para a tabela existente neste form. Recebe o login e
     * senha da SatrtData e passa ao ModelTable
     *
     * @param login
     * @param pw
     */
    public queryForm(String login, String pw) {
        try {
            this.table = new ModelTable(url, login, pw, "select * from cliente");
            this.login = login;
            this.pw = pw;
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Não foi possivel estabelecer conexão \ncom o banco de dados", "Message", 2);
            System.exit(0);
        }
        initComponents();
        jtaQuery.setText("select * from cliente");
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConsultVendedor = new javax.swing.JPanel();
        jbConsulVendedorName = new javax.swing.JButton();
        jbConsulVendedorCod = new javax.swing.JButton();
        jtfVendName = new javax.swing.JTextField();
        jtfConsulVendedorCod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbConsultProdName = new javax.swing.JButton();
        jbConsultProdCod = new javax.swing.JButton();
        jtfProdName = new javax.swing.JTextField();
        jtfProdCod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUltimasConsultas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbUpdateCliente = new javax.swing.JButton();
        jbAtualizarPelaTabela = new javax.swing.JButton();
        jbUpdateVendedores = new javax.swing.JButton();
        jbUpdateProduto = new javax.swing.JButton();
        jbUpdateUsers = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaQuery = new javax.swing.JTextArea();
        jbQuery = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtfNumeroNF = new javax.swing.JTextField();
        jbOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbNameCli = new javax.swing.JButton();
        jbCodCli = new javax.swing.JButton();
        jtfNameCli = new javax.swing.JTextField();
        jtfCodCli = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiVendedores = new javax.swing.JMenuItem();
        jmiEditaInTable = new javax.swing.JMenuItem();
        jmiUsers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jmiSuporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jpConsultVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Vendedor"));
        jpConsultVendedor.setToolTipText("Consultar Vendedor");
        jpConsultVendedor.setName(""); // NOI18N

        jbConsulVendedorName.setText("OK");
        jbConsulVendedorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsulVendedorNameActionPerformed(evt);
            }
        });

        jbConsulVendedorCod.setText("OK");
        jbConsulVendedorCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsulVendedorCodActionPerformed(evt);
            }
        });

        jtfVendName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfVendNameKeyPressed(evt);
            }
        });

        jtfConsulVendedorCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfConsulVendedorCodKeyPressed(evt);
            }
        });

        jLabel1.setText("Digitite o nome ou parte do nome do Vendedor:");

        jLabel2.setText("Digite o codigo do Vendedor:");

        javax.swing.GroupLayout jpConsultVendedorLayout = new javax.swing.GroupLayout(jpConsultVendedor);
        jpConsultVendedor.setLayout(jpConsultVendedorLayout);
        jpConsultVendedorLayout.setHorizontalGroup(
            jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultVendedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultVendedorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfConsulVendedorCod, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsulVendedorCod))
                    .addGroup(jpConsultVendedorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVendName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsulVendedorName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpConsultVendedorLayout.setVerticalGroup(
            jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultVendedorLayout.createSequentialGroup()
                .addGroup(jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfVendName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsulVendedorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpConsultVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfConsulVendedorCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsulVendedorCod))
                .addGap(32, 32, 32))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Produto"));

        jLabel3.setText("Digite o nome ou parte no nome do Produto:");

        jLabel4.setText("Digite o codigo do Produto:");

        jbConsultProdName.setText("OK");
        jbConsultProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultProdNameActionPerformed(evt);
            }
        });

        jbConsultProdCod.setText("OK");
        jbConsultProdCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultProdCodActionPerformed(evt);
            }
        });

        jtfProdName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfProdNameKeyPressed(evt);
            }
        });

        jtfProdCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfProdCodKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultProdName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConsultProdCod)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultProdName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultProdCod))
                .addGap(129, 129, 129))
        );

        jTable1.setModel(table);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ultimas linhas de consulta"));
        jPanel3.setToolTipText("");

        jtUltimasConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane3.setViewportView(jtUltimasConsultas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Você deseja fazer alterações em?"));

        jbUpdateCliente.setText("Clientes");
        jbUpdateCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateClienteActionPerformed(evt);
            }
        });

        jbAtualizarPelaTabela.setText("Atualizar atavés de uma tabela");
        jbAtualizarPelaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarPelaTabelaActionPerformed(evt);
            }
        });

        jbUpdateVendedores.setText("Vendedores");
        jbUpdateVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateVendedoresActionPerformed(evt);
            }
        });

        jbUpdateProduto.setText("Produtos");
        jbUpdateProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateProdutoActionPerformed(evt);
            }
        });

        jbUpdateUsers.setText("Usuários");
        jbUpdateUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jbAtualizarPelaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jbUpdateProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbUpdateCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbUpdateVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbUpdateUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbUpdateVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(jbUpdateUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(jbUpdateProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addComponent(jbUpdateCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAtualizarPelaTabela)
                .addGap(11, 11, 11))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo para consulta MySQL"));

        jtaQuery.setColumns(20);
        jtaQuery.setRows(5);
        jScrollPane2.setViewportView(jtaQuery);

        jbQuery.setText("Query");
        jbQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbQuery))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jbQuery)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar nota fiscal"));

        jLabel7.setText("Digite o numero da nota fiscal:");

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNumeroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbOK)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtfNumeroNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Cliente"));

        jLabel5.setText("Digite o nome ou parte do nome do Cliente:");

        jLabel6.setText("Digite o CPF do Cliente:");

        jbNameCli.setText("OK");
        jbNameCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNameCliActionPerformed(evt);
            }
        });

        jbCodCli.setText("OK");
        jbCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCodCliActionPerformed(evt);
            }
        });

        jtfNameCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNameCliKeyPressed(evt);
            }
        });

        jtfCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodCliKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNameCli, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNameCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCodCli)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNameCli)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtfNameCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbCodCli))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jmiCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cliente.png"))); // NOI18N
        jmiCliente.setText("Clientes");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCliente);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Seller.jpg"))); // NOI18N
        jmiProdutos.setText("Produtos");
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiProdutos);

        jmiVendedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Vendedor.png"))); // NOI18N
        jmiVendedores.setText("Vendedores");
        jmiVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendedoresActionPerformed(evt);
            }
        });
        jMenu2.add(jmiVendedores);

        jmiEditaInTable.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiEditaInTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/list.png"))); // NOI18N
        jmiEditaInTable.setText("Editar na tabela");
        jmiEditaInTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditaInTableActionPerformed(evt);
            }
        });
        jMenu2.add(jmiEditaInTable);

        jmiUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_add.png"))); // NOI18N
        jmiUsers.setText("Usuários");
        jmiUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsersActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUsers);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jmiSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sobre.png"))); // NOI18N
        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jMenu3.add(jmiSobre);

        jmiSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Help.png"))); // NOI18N
        jmiSuporte.setText("Suporte");
        jmiSuporte.setToolTipText("");
        jmiSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSuporteActionPerformed(evt);
            }
        });
        jMenu3.add(jmiSuporte);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpConsultVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpConsultVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Consulta o vendedor pelo nome e deixa os outros campos em braco
     */
    private void jbConsulVendedorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsulVendedorNameActionPerformed
        try {
            table.searchVendedorName(jtfVendName.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfNameCli.setText("");
            jtfCodCli.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsulVendedorNameActionPerformed

    /**
     * Consulta no banco de dados atraves de uma linha especifica de codigo sql
     * chama o metodo populate para que adicione a linha executa em uma tabela
     * de comandos sql executados
     *
     * @param evt
     */
    private void jbQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQueryActionPerformed
        String text = jtaQuery.getText();
        populate();
        try {
            this.table.setQuery(text);
        } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ops! Algodeu errado\nVerifique a sintaxe por favor!", "Message", 2);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbQueryActionPerformed

    /**
     * Consulta o cliente pelo nome e deixa os outros campos em braco
     *
     * @param evt
     */
    private void jbNameCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNameCliActionPerformed
        try {
            table.searchCliName(jtfNameCli.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbNameCliActionPerformed

    /**
     * Consulta o cliente pelo codigo e deixa os outros campos em braco
     *
     * @param evt
     */
    private void jbCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCodCliActionPerformed
        try {
            table.searchCliCod(jtfCodCli.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado", "Message", 2);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbCodCliActionPerformed

    /**
     * Consulta o produto pelo nome e deixa os outros campos em braco
     *
     * @param evt
     */
    private void jbConsultProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultProdNameActionPerformed
        try {
            table.searchProName(jtfProdName.getText());
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
            jtfCodCli.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsultProdNameActionPerformed

    /**
     * Método que insere valores na tabela de ultimas consultas realizadas
     */
    private void populate() {
        TableModel mod = jtUltimasConsultas.getModel();
        try {
            full = jtUltimasConsultas.getValueAt(6, 0).toString();
        } catch (Exception ex) {
        }
        if (full.length() != 0) {
            um = jtUltimasConsultas.getValueAt(0, 0).toString();
            dois = jtUltimasConsultas.getValueAt(1, 0).toString();
            tres = jtUltimasConsultas.getValueAt(2, 0).toString();
            quatro = jtUltimasConsultas.getValueAt(3, 0).toString();
            cinco = jtUltimasConsultas.getValueAt(4, 0).toString();
            seis = jtUltimasConsultas.getValueAt(5, 0).toString();

            mod.setValueAt(jtaQuery.getText(), 0, 0);
            mod.setValueAt(um, 1, 0);
            mod.setValueAt(dois, 2, 0);
            mod.setValueAt(tres, 3, 0);
            mod.setValueAt(quatro, 4, 0);
            mod.setValueAt(cinco, 5, 0);
            mod.setValueAt(seis, 6, 0);
        } else {
            mod.setValueAt(jtaQuery.getText(), line, 0);
            line++;
        }
    }

    /**
     * Consulta o vendedor pelo codigo e deixa os outros campos em braco
     *
     * @param evt
     */
    private void jbConsulVendedorCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsulVendedorCodActionPerformed
        try {
            table.searchVendedorCod(jtfConsulVendedorCod.getText());
            jtfProdCod.setText("");
            jtfProdName.setText("");
            jtfNameCli.setText("");
            jtfCodCli.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado", "Message", 2);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsulVendedorCodActionPerformed

    /**
     * Consulta o produto pelo codigo e deixa os outros campos em braco
     *
     * @param evt
     */
    private void jbConsultProdCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultProdCodActionPerformed
        try {
            table.searchProCod(jtfProdCod.getText());
            jtfVendName.setText("");
            jtfConsulVendedorCod.setText("");
            jtfCodCli.setText("");
            jtfConsulVendedorCod.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado", "Message", 2);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbConsultProdCodActionPerformed

    /**
     * Se pressionado a telca enter no campo de consulta pelo nome do vendedor
     * então será passado uma ação nula ao botão para que execute o código de
     * pesquisa
     *
     * @param evt
     */
    private void jtfVendNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfVendNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbConsulVendedorNameActionPerformed(null);
        }
    }//GEN-LAST:event_jtfVendNameKeyPressed

    /**
     * Se pressionado a telca enter no campo de consulta pelo codigo do vendedor
     * então será passado uma ação nula ao botão para que execute o código de
     * pesquisa
     *
     * @param evt
     */
    private void jtfConsulVendedorCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsulVendedorCodKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbConsulVendedorCodActionPerformed(null);
        }
    }//GEN-LAST:event_jtfConsulVendedorCodKeyPressed

    /**
     * Se pressionado a telca enter no campo de consulta pelo nome do produto
     * então será passado uma ação nula ao botão para que execute o código de
     * pesquisa
     *
     * @param evt
     */
    private void jtfProdNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProdNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbConsultProdNameActionPerformed(null);
        }
    }//GEN-LAST:event_jtfProdNameKeyPressed

    /**
     * Se pressionado a telca enter no campo de consulta pelo codigo do produto
     * então será passado uma ação nula ao botão para que execute o código de
     * pesquisa
     *
     * @param evt
     */
    private void jtfProdCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProdCodKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbConsultProdCodActionPerformed(null);
        }
    }//GEN-LAST:event_jtfProdCodKeyPressed

    /**
     * Se pressionado a telca enter no campo de consulta pelo nome do cliente
     * então será passado uma ação nula ao botão para que execute o código de
     * pesquisa
     *
     * @param evt
     */
    private void jtfNameCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameCliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbNameCliActionPerformed(null);
        }
    }//GEN-LAST:event_jtfNameCliKeyPressed

    /**
     * Se pressionado a telca enter no campo de consulta pelo codigo do cliente
     * então será passado uma ação nula ao botão para que execute o código de
     * pesquisa
     *
     * @param evt
     */
    private void jtfCodCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodCliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCodCliActionPerformed(null);
        }
    }//GEN-LAST:event_jtfCodCliKeyPressed

    /**
     * Passa uma ação nula ao botao de vendedores
     *
     * @param evt
     */
    private void jmiVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendedoresActionPerformed
        jbUpdateVendedoresActionPerformed(null);
    }//GEN-LAST:event_jmiVendedoresActionPerformed

    /**
     * opção de menu - sair, caso queira sair, será chamado o metodo para fechar
     * os objetos e logo após a aplicação será encerrada
     *
     * @param evt
     */
    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Voce realmente deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            table.disconnectFromDatabase();
            System.exit(0);
        }
    }//GEN-LAST:event_jmiExitActionPerformed

    /**
     * Passa uma ação ao botão de clientes
     *
     * @param evt
     */
    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        jbUpdateClienteActionPerformed(evt);
    }//GEN-LAST:event_jmiClienteActionPerformed

    /**
     * Passa uma ação ao botão de produtos
     *
     * @param evt
     */
    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        jbUpdateProdutoActionPerformed(evt);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    /**
     * Abre um painel com uma mensagem de contato ao suporte
     *
     * @param evt
     */
    private void jmiSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSuporteActionPerformed
        JOptionPane.showMessageDialog(null, "Contact Support\n\nEmail: xxxxxxxxxxxxxxxxx\nTel: (xx) xxxx-xxxx");
    }//GEN-LAST:event_jmiSuporteActionPerformed

    /**
     * Abre um painel com uma mensagem sobre a aplicação
     *
     * @param evt
     */
    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Database Unity v1.0 \n All Rights Reserved");
    }//GEN-LAST:event_jmiSobreActionPerformed

    /**
     * Passa uma ação para o botão de atualizar pela tabela
     *
     * @param evt
     */
    private void jmiEditaInTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditaInTableActionPerformed
        jbAtualizarPelaTabelaActionPerformed(evt);
    }//GEN-LAST:event_jmiEditaInTableActionPerformed

    /**
     * Chama o metodo de pequisa de uma nota fiscal passando o numero da nota ao
     * metodo
     *
     * @param evt
     */
    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        table.showNF(jtfNumeroNF.getText());
    }//GEN-LAST:event_jbOKActionPerformed

    /**
     * Abre o novo form passando o login e senha obtidos do StartData
     *
     * @param evt
     */
    private void jmiUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsersActionPerformed
        updateUsers user = new updateUsers(login, pw);
        user.setVisible(true);
    }//GEN-LAST:event_jmiUsersActionPerformed

    /**
     * Abre um form de atualização por uma tabela, antes disto, exibe uma
     * mensagem ao usuário sobre os riscos da atualização
     *
     * @param evt
     */
    private void jbAtualizarPelaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarPelaTabelaActionPerformed
        String message = "Modificar dados através de uma tabela pode ser perigoso quando houver um descuido"
                + ". Você pode modificar utilizando outros métodos.\nDeseja atualizar através da tabela?";
        String title = "Confirmação";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            updateFromTableList updateData = new updateFromTableList(login, pw);
            updateData.setVisible(true);
        }
    }//GEN-LAST:event_jbAtualizarPelaTabelaActionPerformed

    /**
     * Chama o metodo preparedStates para carregar os prepapedStatements logo
     * após abre o form de atualização dos clientes
     *
     * @param evt
     */
    private void jbUpdateClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateClienteActionPerformed
        try {
            table.preparedStatesCliente();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado\nNão foi possivel criar alguns prepared statements", "Message", 2);
        }
        updateClienteForm cliente = new updateClienteForm(table);
        cliente.setVisible(true);
    }//GEN-LAST:event_jbUpdateClienteActionPerformed

    /**
     * Chama o metodo preparedStatesVendedor para carregar os prepapedStatements
     * logo após abre o form de atualização dos vendedores
     *
     * @param evt
     */
    private void jbUpdateVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateVendedoresActionPerformed
        try {
            table.preparedStatesVendedor();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado \nNão foi possivel criar alguns prepared statements", "Message", 2);
        }
        updateVendedor vendedor = new updateVendedor(table);
        vendedor.setVisible(true);
    }//GEN-LAST:event_jbUpdateVendedoresActionPerformed

    /**
     * Chama o metodo preparedStatesProdutos para carregar os prepapedStatements
     * logo após abre o form de atualização dos produtos
     *
     * @param evt
     */
    private void jbUpdateProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateProdutoActionPerformed
        try {
            table.preparedStatesProdutos();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado \nNão foi possivel criar alguns prepared statements", "Message", 2);
        }
        updateProduto produto = new updateProduto(table);
        produto.setVisible(true);
    }//GEN-LAST:event_jbUpdateProdutoActionPerformed

    /**
     * Passa a ação do botão de usuários ao item de menu
     *
     * @param evt
     */
    private void jbUpdateUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateUsersActionPerformed
        jmiUsersActionPerformed(evt);
    }//GEN-LAST:event_jbUpdateUsersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAtualizarPelaTabela;
    private javax.swing.JButton jbCodCli;
    private javax.swing.JButton jbConsulVendedorCod;
    private javax.swing.JButton jbConsulVendedorName;
    private javax.swing.JButton jbConsultProdCod;
    private javax.swing.JButton jbConsultProdName;
    private javax.swing.JButton jbNameCli;
    private javax.swing.JButton jbOK;
    private javax.swing.JButton jbQuery;
    private javax.swing.JButton jbUpdateCliente;
    private javax.swing.JButton jbUpdateProduto;
    private javax.swing.JButton jbUpdateUsers;
    private javax.swing.JButton jbUpdateVendedores;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiEditaInTable;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiSuporte;
    private javax.swing.JMenuItem jmiUsers;
    private javax.swing.JMenuItem jmiVendedores;
    private javax.swing.JPanel jpConsultVendedor;
    private javax.swing.JTable jtUltimasConsultas;
    private javax.swing.JTextArea jtaQuery;
    private javax.swing.JTextField jtfCodCli;
    private javax.swing.JTextField jtfConsulVendedorCod;
    private javax.swing.JTextField jtfNameCli;
    private javax.swing.JTextField jtfNumeroNF;
    private javax.swing.JTextField jtfProdCod;
    private javax.swing.JTextField jtfProdName;
    private javax.swing.JTextField jtfVendName;
    // End of variables declaration//GEN-END:variables
}
